/controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
    cartesian_impedance_controller:
      type: compliant_controllers/GenericCartesianControllerWrapper
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
/cartesian_impedance_controller:
  ros__parameters:
    arm_id: rizon4s
    init_k_pos: 200.0
    init_k_ori: 10.0
    max_step_guard_enabled: true
    ee_frame: flange
    robot_description_node: /robot_state_publisher
    robot_description_param: robot_description
    gravity_compensation_enabled: true
    joint_limit_repulsion:
      enabled: true
      stiffness:
      - 50.0
      damping:
      - 5.0
      margin:
      - 0.15
    impl_library: libcartesian_impedance_impl.so
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    base_frame: base_link
