# This is a namespace agnostic configuration file for Franka FR3 robots.
# See https://github.com/frankarobotics/franka_ros2/blob/humble/franka_bringup/config/controllers.yaml for further reference.


/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98
      enable_overrun: false 

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
        state_interfaces:
          robot_state

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      fr3_arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      cartesian_impedance_controller:
        type: compliant_controllers/GenericCartesianControllerWrapper

      joint_impedance_controller:
        type: compliant_controllers/GenericJointControllerWrapper

      friction_estimation_controller:
        type: compliant_controllers/GenericCartesianControllerWrapper

      friction_estimation_controller_v2:
        type: compliant_controllers/GenericCartesianControllerWrapper

      friction_compensation_controller_v2:
        type: compliant_controllers/GenericCartesianControllerWrapper

/**:
  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 
      lock_sleep_interval: 5
      lock_log_error: true 
      lock_update_success: false 

/**:
  joint_state_broadcaster:
    ros__parameters:
      arm_id: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  cartesian_impedance_controller:
    ros__parameters:
      arm_id: fr3
      init_k_pos: 200.0
      init_k_ori: 10.0
      ee_frame: fr3_link8
      robot_description_node: robot_state_publisher
      robot_description_param: robot_description
      end_effector_profile_node: end_effector_profile_server
      tcp_enabled: true
      end_effector.robot_state_topic: /fr3/franka_robot_state_broadcaster/robot_state
      ee_load_compensation_enabled: false
      impl_library: libcartesian_impedance_impl.so
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  joint_impedance_controller:
    ros__parameters:
      arm_id: fr3
      ee_frame: fr3_link8
      robot_description_node: robot_state_publisher
      robot_description_param: robot_description
      impl_library: libjoint_impedance_impl.so
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  friction_estimation_controller:
    ros__parameters:
      arm_id: fr3
      init_k_pos: 50.0
      init_k_ori: 5.0
      ee_frame: fr3_link8
      robot_description_node: robot_state_publisher
      robot_description_param: robot_description
      ee_load_compensation_enabled: false
      gravity_compensation_enabled: false
      friction_compensation_enabled: false
      friction_compensation:
        scale: 0.0
      update_robot_config: true
      shutdown_when_done: true
      done_marker_file: /tmp/friction_estimation.done
      updated_robot_config_output: /tmp/robot_config.updated.yaml
      robot_profile: ""
      impl_library: libfriction_estimation_impl.so
      q_init: "0,0,0,-1.474803217,0,2.09439510239,0"
      test_joint_index: -1
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  friction_estimation_controller_v2:
    ros__parameters:
      arm_id: fr3
      ee_frame: fr3_link8
      robot_description_node: robot_state_publisher
      robot_description_param: robot_description
      ee_load_compensation_enabled: false
      gravity_compensation_enabled: false
      friction_compensation_enabled: false
      friction_compensation:
        scale: 0.0
      impl_library: libfriction_estimation_impl_v2.so
      plugin_params_file: /home/smihael/local_ws/src/compliant_controllers_demos/config/friction_estimation_v2.toml
      csv_file: /tmp/friction_estimation_measurements_v2.csv
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  friction_compensation_controller_v2:
    ros__parameters:
      arm_id: fr3
      init_k_pos: 50.0
      init_k_ori: 5.0
      ee_frame: fr3_link8
      robot_description_node: robot_state_publisher
      robot_description_param: robot_description
      end_effector_profile_node: end_effector_profile_server
      tcp_enabled: true
      ee_load_compensation_enabled: false
      gravity_compensation_enabled: false
      friction_compensation_enabled: false
      friction_compensation:
        model: hysteresis
        scale: 0.0
        hyst: [0.050000000000000003, 0.050000000000000003, 0.050000000000000003, 0.050000000000000003, 0.050000000000000003, 0.050000000000000003, 0.050000000000000003]
        fvp: [0.23053864929284926, -37.57815721130266, 0.063239399440850913, 8.9461116897567319, -0.61367897327178023, 0.15647987619561726, 0.13086573350945419]
        fcp: [0.38278877822057888, 6.520995810547582, 0.23736505705090602, 20.250746309229442, 1.2479506985237976, 2.6060926861463618, 0.23001647082754176]
        fvn: [-0.3596639516610633, 6.6169534873792273, -0.0099295812948854457, -9.3072584499973061, 0.30278539205069743, -0.14412180199338451, 0.031893898388891992]
        fcn: [1.0776171412958586, 8.1202222990847446, 0.41550376897122482, -17.762495995410092, -0.093872280442755973, -2.1779280543549691, 0.37352581473042679]
      plugin_params_file: /home/smihael/local_ws/src/compliant_controllers_demos/config/friction_compensation_v2.ini
      impl_library: libfriction_compensation_impl_v2.so
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

/**:
  fr3_arm_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      gains:
        fr3_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        fr3_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        fr3_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        fr3_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }
      allow_partial_joints_goal: false
      action_monitor_rate: 20.0
      state_publish_rate: 50.0
      interpolation_method: splines
      constraints:
        stopped_velocity_tolerance: 0.02
        goal_time: 0.0
