<?xml version="1.0"?>
<package format="3">
  <name>franka_onrobot_robotiq</name>
  <version>0.0.1</version>
  <description>Real FR3 accessory bringup based on franka_real.</description>
  <maintainer email="smihael@gmail.com">Mihael Simonic</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>franka_real</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>franka_description</exec_depend>
  <exec_depend>onrobot_ft_ros2</exec_depend>
  <exec_depend>net_ft_description</exec_depend>
  <exec_depend>robotiq_description</exec_depend>
  <exec_depend>robotiq_driver</exec_depend>
  <exec_depend>robotiq_controllers</exec_depend>
  <exec_depend>gripper_controllers</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
